### PR TITLE
Fix display of components on main page with React Router

### LINKED ISSUE #132: Fix routing in App component
We need to fix our routing as there's currently too many components showing on certain client side routes.

We are working on getting this fixed so we will see all we should be on that particular route.

Things like the /signin route will only show the SignIn component.

### PR DESCRIPTION
**Pull request by bryceknz**
Closes #132

### CODE REVIEW

File: client/components/App.jsx [hunk 1]
```diff
@@ -1,18 +1,17 @@
 import React from 'react'
-import { Route } from 'react-router-dom'
+import { Route, Switch } from 'react-router-dom'
 import DropdownModule from './dropdownModule/DropdownModule'
```
Comment (emilyparkes) [inline client/components/App.jsx]: if removed below, perhaps remove import too

**Review by emilyparkes — CHANGES_REQUESTED** [review]

**Review by emilyparkes — APPROVED** [review]
